
# create service records in Solace
# ACL execptions
# ClientProfile
# Clients
# Topic schema : APP/SERVICE/TYPE/OBJECT
# example:       2FSN/DMDIST/REQUEST/>
#                2FSN/DMDIST/EVENT

service-config:
   network:
       nodes: [ hostname:port, host2:port ]
   application:
        name: 2FSN
   service:
       name: DMDIST
       type: DIRECT_NON_PERSIST, JNDI_NON_PERSIST
       pubslishers: [ USER1 ]
       subscribers: [ USER2, USER3 ]
       objects: [ PriceX, PriceY ]


#  System will create the following configuration
#  VPN: 2FSN_VPN
#   Client 2FSN_USER1, 2FSN_USER2, 2FSN_USER3
#    ACLProfileExceotions
#      publish:   2FSN/DMDIST/PriceX/Event
#      publish:   2FSN/DMDIST/PriceX/Request
#
#      subscribe: 2FSN/DMDIST/PriceX/Reply/>
#
#   JNDI Topics:
#      2FSN/
#
#
